### PR TITLE
Socket.IO removal -> Staging

### PR DESCRIPTION
**Pull request by EricRabil**

### CODE REVIEW

**Comment by nullpixel** [comment]
There’s a reason we used socket-io over actual websockets.

**Comment by AppleBetas** [comment]
Reasons boiled down to:
- First thing I saw when completion of the site was rushed and I had a few hours to do everything (bad choice)
- Works with some other browsers that don’t support WS (its 2018 who cares, all that matter have for years)

I’m in favour of scrapping Socket.io.

**Comment by nullpixel** [comment]
I’m not. Our socket io connections are reset every 10 seconds, for reasons unbeknown to me. Socket IO can fall back to using HTTP polling, and I think this is a good fallback considering how cloudflare resets our WS connections the second they’re upgraded. This issue realistically should be investigated more before we can even consider merging this PR into master.

**Comment by AppleBetas** [comment]
The issue referenced above has been fixed (and was a server configuration mistake), for the record.

**Pull request merged**
