### PR TITLE
Solved the "typeof" problem

### PR DESCRIPTION
**Pull request by hebertcisco**
Expression 'typeof this.req.user' evaluates to a string value, but it is incompatibly compared to undefined value.

### CODE REVIEW

**Comment by aydenp** [comment]
~~Have you tested these changes? I don't think `req.user` should ever be a string value.~~

---

Double checked, and it should be the User model. Maybe there's a deeper issue hidden in the code if that's what its evaluating to for you. 

I'm also not sure if `typeof x === String` would ever return true. `typeof` would be a string, as it returns a string representation of the type (`"string"`, `"object"`, etc.), but we are still meaning to check against undefined values there (in your case, I believe it returns a string containing "string", so we'd want `typeof x === "string"` if we wanted to check for strings).

There is an issue in the existing code though (that I think I may have introduced), and its that we check that typeof is `undefined` rather than `"undefined"`. It would be cool if you could adapt your PR to rectify that mistake we made!

**Comment by EricRabil** [comment]
Thanks for opening a PR! I think that contributors and yourself may have mixed up the value that the `typeof` operator returns.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

**Comment by hebertcisco** [comment]
Now it's completely resolved

**Comment by aydenp** [comment]
I'm not sure what `undeclaredVariable` resolves to? Could that be something from another programming language? The check should likely read like `typeof x !== "undefined"`.

**Pull request closed without merging**
