### PR TITLE
Remove: unused 2 line in "moveCamera"

### PR DESCRIPTION
**Pull request by 1c7**
image

This is a very small PR
Only remove 2 line of code.
Because Visual Studio show these 2 line are not used.
it didn't effect any logic

### CODE REVIEW

**Comment by 1c7** [comment]
### By the way, I add pinch&zoom into "place". 
I didn't use interact.js. I tried, but it doesn't work very well.

final solution look something like this:  (check my comment)
https://github.com/taye/interact.js/issues/55

I may send a PR a couple days later from now. feel free to merge or reject. all fine by me

**Comment by 1c7** [comment]
it's been too long, so I just close it myself

**Comment by nullpixel** [comment]
canvas.place is a side project for all of us, and as such we cannot review pull requests instantly. We attempt to do it as soon as we are able.

**Comment by 1c7** [comment]
@nullpixel understandable, I am not complaining :)
Thanks for build this

**Pull request closed without merging**
