### PR TITLE
add microsoft login

### PR DESCRIPTION
**Pull request by TennyZhuang**

### CODE REVIEW

**Review by nullpixel — APPROVED** [review]
Looks good!

**Comment by nullpixel** [comment]
Out of interest, is this something you're adding for the main website or for a fork? I'm not completely sure on if this would be used - feel free to correct me if I'm wrong.

**Comment by TennyZhuang** [comment]
I deploy this repo on my server just for fun and open to Microsoft interns, so I make a fork and add microsoft account login support, then I think contributing to the original website is better~

**Comment by nullpixel** [comment]
Awesome. Merging.

**Pull request merged**
