### PR TITLE
Add OAuth support for Reddit, Discord, Twitter, Github, Facebook and Google

### PR DESCRIPTION
**Pull request by Mstrodl**
This reverts commit 7a8bac13d5394e350a137abde2cec00de46cf20d.

#40

### CODE REVIEW

**Comment by deadbaed** [comment]
why would you revert that?

**Comment by Mstrodl** [comment]
It reverts the commit that removed my code (Because null didn't rewind time) @ploctaux

**Comment by nullpixel** [comment]
I requested this. I meant to rewrite history, but didn't

**Comment by Mstrodl** [comment]
Also, @nullpixel1 I think there may be a problem with my install... I try and use `User.findOnce()` in passport.js on my laptop and it works fine, but when I push it to my server it gives me:
```
TypeError: User.findOne is not a function
```

**Comment by deadbaed** [comment]
oh okay @Mstrodl

**Comment by Mstrodl** [comment]
Never mind! I figured it out! For some reason we don't check if there's a failure connecting to Mongo and I had MongoDB listening on the wrong interface

**Comment by deadbaed** [comment]
why not through facebook? i know people that only use facebook for sites sign in
and they dont have google accounts

**Comment by Mstrodl** [comment]
@ploctaux I actually meant to add Facebook but I was too tired to do it. I might to that tonight.

**Comment by Mstrodl** [comment]
Added Facebook support (And Github a little bit ago) @ploctaux

**Comment by deadbaed** [comment]
oh awesome! @Mstrodl !!

**Comment by Mstrodl** [comment]
*Bump*

**Comment by nullpixel** [comment]
Willing to merge into develop, but I don't have time to review and ab is doing other things atm

**Comment by Mstrodl** [comment]
Didn't we already review it? It's basically the same as back then @nullpixel1

**Comment by nullpixel** [comment]
That, and the fact we need to now get oauth tokens for all those providers places it as fairly low prio. Once @AppleBetas is done w/ admin, I'll merge then because we can have more time dedicated to thorough testing of this PR.

**Comment by Mstrodl** [comment]
Okey dokey. Once this is merged, I also have a user settings page more-or-less working

**Pull request merged**
